fix(CLOUDDST-25034): changed rh-sign-image-cosign to internal requests
Running signing in internal requests improves performance.
Newly created pipeline cosign-signing-pipeline also checks if
signature for given manifest reference and digest already exists.
If so, signing itself is skipped

Signed-off-by: Jindrich Luza <jluza@redhat.com>

diff --git a/tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml b/tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
--- a/tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
+++ b/tasks/rh-sign-image-cosign/tests/test-rh-sign-image-cosign-single-component.yaml
@@ -40,6 +40,49 @@ spec:
               cat > "$(workspaces.data.path)/signRegistryAccess.txt" << EOF
               test-product/test-image2
               EOF
+
+              cat > "$(workspaces.data.path)/data.json" << EOF
+              {
+                "mapping": {
+                  "defaults": {
+                    "pushSourceContainer": "true"
+                  }
+                },
+                "sign": {
+                  "request": "cosign-signing-pipeline",
+                  "requestType": "internal-request",
+                  "configMapName": "signing-config-map"
+                }
+              }
+              EOF
+
+              cat > "$(workspaces.data.path)/release_plan_admission.json" << EOF
+              {
+                "spec": {
+                  "pipeline": {
+                    "pipelineRef": {
+                      "resolver": "git",
+                      "params": [
+                        {
+                          "name": "url",
+                          "value": "https://localhost.git"
+                        },
+                        {
+                          "name": "revision",
+                          "value": "main"
+                        },
+                        {
+                          "name": "pathInRepo",
+                          "value": "pipelines/abc/abc.yaml"
+                        }
+                      ]
+                    },
+                    "serviceAccountName": "default"
+                  }
+                }
+              }
+              EOF
+
     - name: run-task
       taskRef:
         name: rh-sign-image-cosign
@@ -50,6 +93,16 @@ spec:
           value: 'test-cosign-secret'
         - name: signRegistryAccessPath
           value: signRegistryAccess.txt
+        - name: releasePlanAdmissionPath
+          value: release_plan_admission.json
+        - name: dataPath
+          value: data.json
+        - name: taskGitRevision
+          value: "main"
+        - name: taskGitUrl
+          value: "http://localhost"
+        - name: pipelineRunUid
+          value: $(context.pipelineRun.uid)
       workspaces:
         - name: data
           workspace: tests-workspace
@@ -70,20 +123,61 @@ spec:
               _TEST_PUB_REPO1="registry.stage.redhat.io/test-product/test-image2"
               _TEST_PUB_REPO2="registry.access.stage.redhat.com/test-product/test-image2"
               _TEST_REPO="quay.io/redhat-pending/test-product----test-image2"
+              # shellcheck disable=SC2034
+              foundReferences=()
+              # shellcheck disable=SC2034
+              foundDigests=()
+              # shellcheck disable=SC2034
+              foundIdentities=()
+              while IFS= read -r name; do
+                ir=$(kubectl get internalrequest "$name" -o json)
+                params=$(jq -r ".spec.params" <<< "$ir")
+                refValue=$(jq -r '.reference' <<< "${params}")
+                digestValue=$(jq -r '.manifest_digest' <<< "${params}")
+                identityValue=$(jq -r '.identity' <<< "${params}")
+                echo "$params $refValue"
+                foundReferences+=("${refValue}")
+                foundDigests+=("${digestValue}")
+                foundIdentities+=("${identityValue}")
+              done < <(cat "$(workspaces.data.path)/mock_internal-request-names.txt")
 
-              CALLS=$(cat "$(workspaces.data.path)/mock_skopeo_calls")
-              EXPECTED="inspect --raw docker://quay.io/redhat-user-workloads/test-product/test-image2@sha256:2222"
-              test "$CALLS" = "$EXPECTED"
+              expectedReferences=()
+              expectedReferences+=("${_TEST_REPO}:t1")
+              expectedReferences+=("${_TEST_REPO}:t2")
+              expectedDigests=()
+              expectedDigests+=("sha256:2222")
+              expectedIdentities=()
+              expectedIdentities+=("${_TEST_PUB_REPO1}:t1")
+              expectedIdentities+=("${_TEST_PUB_REPO1}:t2")
+              expectedIdentities+=("${_TEST_PUB_REPO2}:t1")
+              expectedIdentities+=("${_TEST_PUB_REPO2}:t2")
 
-              CALLS=$(cat "$(workspaces.data.path)/mock_cosign_calls")
-              COSIGN_COMMON="-t 3m0s sign --tlog-upload=false --key aws://arn:mykey --sign-container-identity"
-              EXPECTED=$(cat <<EOF
-              $COSIGN_COMMON ${_TEST_PUB_REPO1}:t1 ${_TEST_REPO}@sha256:2222
-              $COSIGN_COMMON ${_TEST_PUB_REPO1}:t2 ${_TEST_REPO}@sha256:2222
-              $COSIGN_COMMON ${_TEST_PUB_REPO2}:t1 ${_TEST_REPO}@sha256:2222
-              $COSIGN_COMMON ${_TEST_PUB_REPO2}:t2 ${_TEST_REPO}@sha256:2222
-              EOF
-              )
-              test "$CALLS" = "$EXPECTED"
+              differenceReferences=$(echo "${expectedReferences[@]}" "${foundReferences[@]}" | tr ' ' '\n' \
+                | sort | uniq -u)
+
+              if [ -n "${differenceReferences}" ] ; then
+                echo "error: references expected compared to found do not match"
+                echo ""
+                echo "${differenceReferences}"
+                exit 1
+              fi
+              differenceIdentities=$(echo "${expectedIdentities[@]}" "${foundIdentities[@]}" | tr ' ' '\n' \
+                | sort | uniq -u)
+
+              if [ -n "${differenceIdentities}" ] ; then
+                echo "error: identities expected compared to found do not match"
+                echo ""
+                echo "${differenceIdentities}"
+                exit 1
+              fi
+              differenceDigests=$(echo "${expectedDigests[@]}" "${foundDigests[@]}" | tr ' ' '\n' \
+                | sort | uniq -u)
+
+              if [ -n "${differenceDigests}" ] ; then
+                echo "error: digests expected compared to found do not match"
+                echo ""
+                echo "${differenceDigests}"
+                exit 1
+              fi
       runAfter:
         - run-task
