feat(CLOUDDST-25758): use pubtools-sign  sign and upload images
internal request request-and-upload-signature was transfered to
use pubtools-sign and pubtools-pyxis to sign and upload signatures.
With that, internal requests are now called with multiple references and
digests. Batch size is limited by params string length which is set by
default to 4096. Retry mechanism in signing was also removed as it's
already included in pubtools-sign

Signed-off-by: Jindrich Luza <jluza@redhat.com>

diff --git a/tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml b/tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
--- a/tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
+++ b/tasks/internal/request-and-upload-signature/request-and-upload-signature.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: request-and-upload-signature
   labels:
-    app.kubernetes.io/version: "1.0.0"
+    app.kubernetes.io/version: "2.0.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -18,16 +18,18 @@ spec:
   params:
     - description: A docker image of operator-pipeline-images for the steps to run in.
       name: pipeline_image
-      default: "quay.io/redhat-isv/operator-pipelines-images:released"
+      default: "quay.io/konflux-ci/release-service-utils:0cf1c7923de64484f8737c0def90b74fe866040f"
       type: string
-    - description: Manifest digest for the signed content, usually in the format sha256:xxx
-      name: manifest_digest
-      type: string
-    - description: Docker reference for the signed content, e.g. registry.redhat.io/redhat/community-operator-index:v4.9
-      name: reference
+    - description: |
+        List of space separated manifest digests for the signed content, usually in the format sha256:xxx
+      name: manifest_digests
       type: string
     - description: Name of the user that requested the signing, for auditing purposes
       name: requester
+    - description: |
+        List of space separated docker references for the signed content,
+        e.g. registry.com/ns/image:v4.9 registry.com/ns/image:v4.10
+      name: references
       type: string
     - default: 4096R/55A34A82 SHA-256
       description: The signing key id that the content is signed with
@@ -46,6 +48,10 @@ spec:
     - description: The key within the Kubernetes secret that contains the Pyxis SSL key.
       name: pyxis_ssl_key_file_name
       type: string
+    - description: Number of threads used to upload signatures to pyxis
+      name: pyxis_threads
+      type: string
+      default: 5
     - default: operatorpipelines
       description: Client name to connect to umb, usually a service account name
       name: umb_client_name
@@ -80,34 +86,18 @@ spec:
       default: "signing_response.json"
       type: string
   steps:
-    - name: request-signature
+    - name: build-pubtools-sign-config
       image: "$(params.pipeline_image)"
       workingDir: "$(workspaces.data.path)"
       env:
-        - name: UmbCert
-          valueFrom:
-            secretKeyRef:
-              name: $(params.umb_ssl_cert_secret_name)
-              key: $(params.umb_ssl_cert_file_name)
-        - name: UmbKey
-          valueFrom:
-            secretKeyRef:
-              name: $(params.umb_ssl_cert_secret_name)
-              key: $(params.umb_ssl_key_file_name)
         - name: UMB_CERT_PATH
           value: "/tmp/crt"
         - name: UMB_KEY_PATH
           value: "/tmp/key"
-        - name: manifest_digest
-          value: $(params.manifest_digest)
-        - name: reference
-          value: $(params.reference)
         - name: requester
           value: $(params.requester)
-        - name: sig_key_id
-          value: $(params.sig_key_id)
-        - name: sig_key_name
-          value: $(params.sig_key_name)
+        - name: manifest_digests
+          value: $(params.manifest_digests)
         - name: umb_client_name
           value: $(params.umb_client_name)
         - name: umb_listen_topic
@@ -118,49 +108,159 @@ spec:
           value: $(params.umb_url)
         - name: signature_data_file
           value: "$(params.signature_data_file)"
+        - name: CA_BUNDLE
+          value: /etc/pki/tls/certs/ca-bundle.crt
       script: |
         #!/usr/bin/env /bin/bash
         set -x
-        
-        MAX_RETRIES=3
-        RETRY_DELAY=5 # Initial delay
-        
-        set +x
-        # This helps with Shellcheck warning
-        echo "${UmbCert:?}" > /tmp/crt
-        echo "${UmbKey:?}" > /tmp/key
+        cat <<EOF > /tmp/pubtools-sign-config.yaml
+        msg_signer:
+          messaging_brokers:
+            - "${umb_url}"
+          messaging_cert_key: /tmp/umb.pem
+          messaging_ca_cert: ${CA_BUNDLE}
+          topic_send_to: ${umb_publish_topic}
+          topic_listen_to: queue://Consumer.${requester}.{task_id}.${umb_listen_topic}.{task_id}
+          environment: prod
+          service: ${umb_client_name}
+          timeout: 7
+          retries: 1
+          send_retries: 2
+          message_id_key: request_id
+          log_level: debug
+        EOF
+
+    - name: request-signature
+      image: "$(params.pipeline_image)"
+      workingDir: "$(workspaces.data.path)"
+      env:
+        - name: umb_cert
+          valueFrom:
+            secretKeyRef:
+              name: $(params.umb_ssl_cert_secret_name)
+              key: $(params.umb_ssl_cert_file_name)
+        - name: umb_key
+          valueFrom:
+            secretKeyRef:
+              name: $(params.umb_ssl_cert_secret_name)
+              key: $(params.umb_ssl_key_file_name)
+        - name: manifest_digests
+          value: $(params.manifest_digests)
+        - name: references
+          value: $(params.references)
+        - name: sig_key_name
+          value: "$(params.sig_key_name)"
+        - name: signature_data_file
+          value: "$(params.signature_data_file)"
+      script: |
+        #!/usr/bin/env /bin/bash
+        echo "${umb_cert:?}" > /tmp/umb.pem
+        echo "${umb_key:?}" >> /tmp/umb.pem
         set -x
-        
-        echo "Requesting signing from RADAS"
-        for ((i=1; i<=MAX_RETRIES; i++)); do
-          if request-signature \
-            --manifest-digest "${manifest_digest}" \
-            --output "${signature_data_file:?}" \
-            --reference "${reference}" \
-            --requester "${requester}" \
-            --sig-key-id "${sig_key_id}" \
-            --sig-key-name "${sig_key_name}" \
-            --umb-client-name "${umb_client_name}" \
-            --umb-listen-topic "${umb_listen_topic}" \
-            --umb-publish-topic "${umb_publish_topic}" \
-            --umb-url "${umb_url}" \
-            --verbose
-          then
-            echo "request-signature command succeeded."
-            break
-          elif [ $i -eq $MAX_RETRIES ]; then
-            echo "Max retries reached. Exiting."
-            exit 1
-          else
-            echo "Attempt $i failed. Retrying in $RETRY_DELAY seconds..."
-            sleep $RETRY_DELAY
-            RETRY_DELAY=$((RETRY_DELAY * 2))  # Exponential backoff
-          fi
+        declare -a reference_args=()
+        declare -a digest_args=()
+        for reference in "${references[@]}"; do
+          reference_args+=("--reference")
+          reference_args+=("${reference}")
         done
-        
-        SIG_DATA=$(cat "${signature_data_file:?}")
-        echo "${SIG_DATA}"
-        echo "signature data file: ${signature_data_file:?}"
+        for digest in "${manifest_digests[@]}"; do
+          digest_args+=("--digest")
+          digest_args+=("${digest}")
+        done
+        pubtools-sign-msg-container-sign \
+          --signing-key "${sig_key_name}" \
+          --config /tmp/pubtools-sign-config.yaml "${reference_args[@]}" "${digest_args[@]}" \
+          --task-id $(context.taskRun.uid) > "$(workspaces.data.path)/signing_response.json"
+    - name: check-signing-response
+      image: "$(params.pipeline_image)"
+      workingDir: "$(workspaces.data.path)"
+      env:
+        - name: signature_data_file
+          value: "$(params.signature_data_file)"
+      script: |
+        #!/usr/bin/env /bin/bash
+        set -xe
+        cat "$(workspaces.data.path)/signing_response.json"
+        STATUS=$(cat "$(workspaces.data.path)/signing_response.json" | jq ".signer_result.status" | tr -d \")
+        ERRORS=$(cat "$(workspaces.data.path)/signing_response.json" | jq ".signer_result.error_message")
+        # pubtools-sign response format:
+        #
+        # {
+        #   "signer_result": {
+        #     "status": ok|error,
+        #     "error_message": ""
+        #   },
+        #   "operation_results": [
+        #     [
+        #       {
+        #         "i": int,
+        #         "msg": {
+        #           "errors": [],
+        #           "manifest_digest": <digest>,
+        #           "pub_task_id": <task-id-identifier>,
+        #           "repo": <repository>,
+        #           "request_id": <radas-request-id>,
+        #           "request_received_time": <ISO-8601-date>
+        #           "requested_by": <name-in-certificate>,
+        #           "sig_key_id": <signing-key-id>,
+        #           "sig_keyname": <signing-key-name>,
+        #           "signature_type": <signiture-type>,
+        #           "signed_claim": <signed-claim-data>,
+        #           "signing_server_requested": <ISO-8601-date>,
+        #           "signing_server_responded": <ISO-8601-date>,
+        #           "signing_status": str
+        #         },
+        #         "msg_id": <msg-id>,
+        #         "timestamp": <int-timestamp>,
+        #         "topic": <response-topic>,
+        #         "username": <username>
+        #       },
+        #       # message headers
+        #       {
+        #         "amq6100_originalDestination": <response-topic>,
+        #         "content-type": "<content-type>,
+        #         "amq6100_destination": <full-response-topic>
+        #       }
+        #     ],
+        #   ],
+        #   "operation": {
+        #     "digests": [
+        #       <digest>
+        #     ],
+        #     "references": [
+        #       <container-reference>
+        #     ],
+        #     "signing_key": <signing-key-id>
+        #     "task_id": <pub-task>
+        #   },
+        #   "signing_key": <signing-key-id>
+        # }
+
+        SIGNATURE_ERRORS=$(cat "$(workspaces.data.path)/signing_response.json" |\
+          jq -cM ".operation_results.[]|.[0].msg.errors")
+        if [ "$SIGNATURE_ERRORS" != "[]" ]; then
+          echo "Signing failed with error: ${SIGNATURE_ERRORS}"
+          exit 1
+        fi
+
+        SIGNATURE_DATA=$(
+          cat "$(workspaces.data.path)/signing_response.json" | \
+          jq -cM "[
+            [.operation_results, .operation.references]|
+            transpose|
+            .[]|
+            {reference:.[1], 
+             digest:.[0][0].msg.manifest_digest,
+             repository:.[0][0].msg.repo,
+             signature_data:.[0][0].msg.signed_claim,
+             sig_key_id: .[0][0].msg.sig_key_id}
+          ]")
+        if [ "${STATUS}" != "ok" ]; then
+          echo "Signing failed with error: ${ERRORS}"
+          exit 1
+        fi
+        echo "${SIGNATURE_DATA}" > "${signature_data_file}"
+
     - name: upload-signature
       image: "$(params.pipeline_image)"
       workingDir: "$(workspaces.data.path)"
@@ -181,22 +281,21 @@ spec:
           value: "/tmp/pyxisKey"
         - name: pyxis_url
           value: $(params.pyxis_url)
+        - name: pyxis_threads
+          value: "$(params.pyxis_threads)"
         - name: signature_data_file
           value: "$(params.signature_data_file)"
       script: |
-        #!/bin/bash
-        set -xe
-        
-        set +x
+        #!/usr/bin/env /bin/bash
         # This helps with Shellcheck warning
-        echo "${PyxisCert:?}" > /tmp/pyxisCert
-        echo "${PyxisKey:?}" > /tmp/pyxisKey
+        echo "${PyxisCert:?}" > "${PYXIS_CERT_PATH}"
+        echo "${PyxisKey:?}" > "${PYXIS_KEY_PATH}"
         set -x
-        
-        echo "Signature verified. Uploading to Pyxis sigstore"
-        upload-signature \
-          --pyxis-url "${pyxis_url:?}" \
-          --signature-data "${signature_data_file:?}" \
-          --verbose
+        pubtools-pyxis-upload-signatures \
+          --pyxis-server "${pyxis_url}" \
+          --ssl-crtfile "${PYXIS_CERT_PATH}" \
+          --ssl-keyfile "${PYXIS_KEY_PATH}" \
+          --request-threads "${pyxis_threads}" \
+          --signature-data @"${signature_data_file}"
   workspaces:
     - name: data
diff --git a/tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-failure.yaml b/tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-failure.yaml
--- a/tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-failure.yaml
+++ b/tasks/internal/request-and-upload-signature/tests/test-request-and-upload-signature-failure.yaml
@@ -2,10 +2,12 @@
 apiVersion: tekton.dev/v1
 kind: Pipeline
 metadata:
-  name: test-request-and-upload-signature
+  name: test-request-and-upload-signature-failure
+  annotations:
+    test/assert-task-failure: "run-task"
 spec:
   description: |
-    Run the request-and-upload-signature task and make sure that task succeeds
+    Run the request-and-upload-signature with error in signer response 
   workspaces:
     - name: tests-workspace
   tasks:
@@ -24,7 +26,7 @@ spec:
               set -eux
               cat << EOF | jq -Mc > "$(workspaces.data.path)/mocked_signing_response"
               {
-                "signer_result": {"status": "ok", "error_message": ""},
+                "signer_result": {"status": "error", "error_message": "test-error"},
                 "operation_results": [
                   [
                     {"i": 1,
@@ -44,27 +46,29 @@ spec:
                        "signing_server_responded": "3000-01-01T01:01:02.000000",
                        "signing_status": "success"
                      },
-                     "msg_id": "msg-id-1",
-                     "timestamp": 1738685708,
-                     "topic": "/topic/VirtualTopic.eng.test.dist.sign.123456",
-                     "username": "1001030000"
+                    "msg_id": "msg-id-1",
+                    "timestamp": 1738685708,
+                    "topic": "/topic/VirtualTopic.eng.test.dist.sign.123456",
+                    "username": "1001030000"
                     },
                     {"amq6100_originalDestination": "topic://VirtualTopic.eng.test.dist.sign.123456",
                      "content-type": "text/plain",
                      "amq6100_destination": "queue://Consumer.test-user.123456.VirtualTopic.eng.test.dist.sign.123456"
                     }
-                  ]],
+                  ]
+                ],
                 "operation": {
                   "digests": ["sha256:123456"],
                   "references": ["registry.redhat.io/myproduct/myrepo:abc"],
-                  "signing_key": "test-signing-key",
-                  "task_id": "123456"},
-                  "signing_key": "test-signing-key"
+                  "signing_key": "test-signing-key", "task_id": "123456"
+                },
+                "signing_key": "test-signing-key"
               }
               EOF
               touch "$(workspaces.data.path)/mock_pubtools-pyxis-upload-signatures.txt"
               touch "$(workspaces.data.path)/signing_response.json"
               chmod 0777 -R "$(workspaces.data.path)"
+              cat "$(workspaces.data.path)/mocked_signing_response"
     - name: run-task
       taskRef:
         name: request-and-upload-signature
@@ -76,7 +80,7 @@ spec:
         - name: references
           value: "registry.redhat.io/myproduct/myrepo:abc"
         - name: requester
-          value: tom
+          value: iamgoingtofail
         - value: 4096R/55A34A82 SHA-256
           name: sig_key_id
         - value: containerisvsign
@@ -110,3 +114,24 @@ spec:
           workspace: tests-workspace
       runAfter:
         - setup
+    - name: check-result
+      workspaces:
+        - name: data
+          workspace: tests-workspace
+      taskSpec:
+        workspaces:
+          - name: data
+        steps:
+          - name: check-result
+            image: quay.io/konflux-ci/release-service-utils:2ddb2b1e7b406674273a2aa3d3e4e92b78cdf625
+            script: |
+              #!/usr/bin/env sh
+              set -eux
+
+              if [ "$(cat "$(workspaces.data.path)/request-signature-failure-count.txt")" != 3 ]; then
+                echo Error: request-signature was expected to be fail 3 times. Actual calls:
+                cat "$(workspaces.data.path)/request-signature-failure-count.txt"
+                exit 1
+              fi
+      runAfter:
+        - run-task
